language: ruby

before_install:
  - gem update bundler

matrix:
  include:
    - rvm: 2.1.2
      gemfile: gemfiles/4.0.gemfile
    - rvm: 2.2.2
      gemfile: gemfiles/4.1.gemfile
    - rvm: 2.3.1
      gemfile: gemfiles/4.2.gemfile

install:
  - "travis_retry bundle install"
